export const emojisArray = [
  { emoji: "😀", title: "Grinning Face" },
  { emoji: "😃", title: "Smiling Face with Open Mouth" },
  { emoji: "😄", title: "Smiling Face with Open Mouth and Smiling Eyes" },
  { emoji: "😁", title: "Grinning Face with Smiling Eyes" },
  { emoji: "😆", title: "Smiling Face with Open Mouth and Closed Eyes" },
  { emoji: "😅", title: "Smiling Face with Open Mouth and Cold Sweat" },
  { emoji: "😂", title: "Face with Tears of Joy" },
  { emoji: "🤣", title: "Rolling on the Floor Laughing" },
  { emoji: "😊", title: "Smiling Face with Smiling Eyes" },
  { emoji: "😇", title: "Smiling Face with Halo" },
  { emoji: "🙂", title: "Slightly Smiling Face" },
  { emoji: "🙃", title: "Upside-Down Face" },
  { emoji: "😉", title: "Winking Face" },
  { emoji: "😌", title: "Relieved Face" },
  { emoji: "😍", title: "Smiling Face with Heart-Shaped Eyes" },
  { emoji: "🥰", title: "Smiling Face with Hearts" },
  { emoji: "😘", title: "Face Blowing a Kiss" },
  { emoji: "😗", title: "Kissing Face" },
  { emoji: "😙", title: "Kissing Face with Smiling Eyes" },
  { emoji: "😚", title: "Kissing Face with Closed Eyes" },
  { emoji: "😋", title: "Face Savoring Food" },
  { emoji: "😛", title: "Face with Tongue" },
  { emoji: "😜", title: "Winking Face with Tongue" },
  { emoji: "🤪", title: "Zany Face" },
  { emoji: "😝", title: "Squinting Face with Tongue" },
  { emoji: "🤑", title: "Money-Mouth Face" },
  { emoji: "🤗", title: "Hugging Face" },
  { emoji: "🤭", title: "Face with Hand Over Mouth" },
  { emoji: "🤫", title: "Shushing Face" },
  { emoji: "🤔", title: "Thinking Face" },
  { emoji: "🤐", title: "Zipper-Mouth Face" },
  { emoji: "🤨", title: "Face with Raised Eyebrow" },
  { emoji: "😐", title: "Neutral Face" },
  { emoji: "😑", title: "Expressionless Face" },
  { emoji: "😶", title: "Face Without Mouth" },
  { emoji: "😏", title: "Smirking Face" },
  { emoji: "😒", title: "Unamused Face" },
  { emoji: "🙄", title: "Face with Rolling Eyes" },
  { emoji: "😬", title: "Grimacing Face" },
  { emoji: "🤥", title: "Lying Face" },
  { emoji: "😔", title: "Pensive Face" },
  { emoji: "😪", title: "Sleepy Face" },
  { emoji: "🤤", title: "Drooling Face" },
  { emoji: "😴", title: "Sleeping Face" },
  { emoji: "😷", title: "Face with Medical Mask" },
  { emoji: "🤒", title: "Face with Thermometer" },
  { emoji: "🤕", title: "Face with Head-Bandage" },
  { emoji: "🤢", title: "Nauseated Face" },
  { emoji: "🤮", title: "Face Vomiting" },
  { emoji: "🤧", title: "Sneezing Face" },
  { emoji: "🥵", title: "Hot Face" },
  { emoji: "🥶", title: "Cold Face" },
  { emoji: "🥴", title: "Woozy Face" },
  { emoji: "😵", title: "Dizzy Face" },
  { emoji: "🤯", title: "Exploding Head" },
  { emoji: "🤠", title: "Cowboy Hat Face" },
  { emoji: "😎", title: "Smiling Face with Sunglasses" },
  { emoji: "🤓", title: "Nerd Face" },
  { emoji: "🧐", title: "Face with Monocle" },
  { emoji: "😕", title: "Confused Face" },
  { emoji: "😟", title: "Worried Face" },
  { emoji: "🙁", title: "Slightly Frowning Face" },
  { emoji: "☹️", title: "Frowning Face" },
  { emoji: "😮", title: "Face with Open Mouth" },
  { emoji: "😯", title: "Hushed Face" },
  { emoji: "😲", title: "Astonished Face" },
  { emoji: "😳", title: "Flushed Face" },
  { emoji: "🥺", title: "Pleading Face" },
  { emoji: "😦", title: "Frowning Face with Open Mouth" },
  { emoji: "😧", title: "Anguished Face" },
  { emoji: "😨", title: "Fearful Face" },
  { emoji: "😩", title: "Weary Face" },
  { emoji: "😓", title: "Downcast Face with Sweat" },
  { emoji: "😥", title: "Sad but Relieved Face" },
  { emoji: "🤬", title: "Face with Symbols Over Mouth" },
  { emoji: "😤", title: "Face with Steam From Nose" },
  { emoji: "👻", title: "Ghost" },
  { emoji: "💀", title: "Skull" },
  { emoji: "☠️", title: "Skull and Crossbones" },
  { emoji: "👽", title: "Alien" },
  { emoji: "👾", title: "Alien Monster" },
  { emoji: "🤖", title: "Robot" },
  { emoji: "🎃", title: "Jack-O-Lantern" },
  { emoji: "😺", title: "Grinning Cat" },
  { emoji: "😸", title: "Grinning Cat with Smiling Eyes" },
  { emoji: "😹", title: "Cat with Tears of Joy" },
  { emoji: "😻", title: "Smiling Cat with Heart-Eyes" },
  { emoji: "😼", title: "Cat with Wry Smile" },
  { emoji: "🙀", title: "Weary Cat" },
  { emoji: "😿", title: "Crying Cat" },
  { emoji: "😾", title: "Pouting Cat" },
  { emoji: "💩", title: "Pile of Poo" },
  { emoji: "👌", title: "OK Hand" },
  { emoji: "✌️", title: "Victory Hand" },
  { emoji: "🤞", title: "Crossed Fingers" },
  { emoji: "🤟", title: "Love-You Gesture" },
  { emoji: "🤘", title: "Sign of the Horns" },
  { emoji: "🤙", title: "Call Me Hand" },
  { emoji: "☝️", title: "Index Pointing Up" },
  { emoji: "🖕", title: "Reversed Hand with Middle Finger Extended" },
  { emoji: "✊", title: "Raised Fist" },
  { emoji: "👊", title: "fits hand" },
  { emoji: "🤛", title: "Left-Facing Fist" },
  { emoji: "🤜", title: "Right-Facing Fist" },
  { emoji: "👏", title: "Clapping Hands" },
  { emoji: "🙌", title: "Raising Hands" },
  { emoji: "👐", title: "Open Hands" },
  { emoji: "🤲", title: "Palms Up Together" },
  { emoji: "🤝", title: "Handshake" },
  { emoji: "🙏", title: "Folded Hands" },
  { emoji: "✍️", title: "Writing Hand" },
  { emoji: "💅", title: "Nail Polish" },
  { emoji: "🤳", title: "Selfie" },
  { emoji: "💪", title: "Muscle" },
  { emoji: "🦵", title: "Leg" },
  { emoji: "🦶", title: "Foot" },
  { emoji: "👂", title: "Ear" },
  { emoji: "👃", title: "Nose" },
  { emoji: "🧠", title: "Brain" },
  { emoji: "🫀", title: "Anatomical Heart" },
  { emoji: "🫁", title: "Lungs" },
  { emoji: "🩸", title: "Drop of Blood" },
  { emoji: "🦷", title: "Tooth" },
  { emoji: "🦴", title: "Bone" },
  { emoji: "👀", title: "Eyes" },
  { emoji: "👁", title: "Eye" },
];
